name: "Quick NixOS Diagnostics"

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main, master ]
    paths: [ '**.nix' ]

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Basic flake diagnostics
      run: |
        echo "🔍 Nix Environment:"
        nix --version
        nix flake show --json | head -20
        
        echo "🔍 Flake inputs:"
        nix flake metadata
        
        echo "🔍 System evaluation test:"
        nix eval .#nixosConfigurations.centaur.config.system.name || echo "❌ System eval failed"
        
        echo "🔍 Kernel configuration:"
        nix eval .#nixosConfigurations.centaur.config.boot.kernelPackages.kernel.pname || echo "❌ Kernel eval failed"
        nix eval .#nixosConfigurations.centaur.config.boot.kernelPackages.kernel.version || echo "❌ Kernel version eval failed"
        
        echo "🔍 Home Manager test:"
        nix eval .#nixosConfigurations.centaur.config.home-manager --apply 'x: "hm-configured"' || echo "❌ Home Manager not configured"

    - name: Dry run with error capture
      run: |
        echo "🔍 Performing focused dry run..."
        nix build .#nixosConfigurations.centaur.config.system.build.toplevel --dry-run --verbose 2>&1 | \
        grep -E "(error|failed|missing|not found|store.*not.*nix)" | \
        head -20 || echo "✅ No obvious errors in dry run"

    - name: Check problematic components
      run: |
        echo "🔍 Testing individual components..."
        
        echo "Testing bootloader:"
        nix eval .#nixosConfigurations.centaur.config.boot.loader.systemd-boot.enable || echo "❌ Bootloader eval failed"
        
        echo "Testing kernel packages:"
        nix eval .#nixosConfigurations.centaur.config.boot.kernelPackages.kernel.drvPath || echo "❌ Kernel package eval failed"
        
        echo "Testing hyprland:"
        nix eval .#nixosConfigurations.centaur.config.programs.hyprland.enable || echo "❌ Hyprland eval failed"
        
        echo "Testing environment packages:"
        nix eval .#nixosConfigurations.centaur.config.environment.systemPackages --apply 'pkgs: builtins.length pkgs' || echo "❌ System packages eval failed"

    - name: Store path investigation
      run: |
        echo "🔍 Store path analysis..."
        echo "Total store items: $(find /nix/store -maxdepth 1 -type d | wc -l)"
        echo "Linux-related items: $(find /nix/store -name "*linux*" -type d | wc -l)"
        echo "Module-related items: $(find /nix/store -name "*module*" -type d | wc -l)"
        
        echo "Sample Linux store paths:"
        find /nix/store -name "*linux*" -type d | head -5 || echo "No Linux paths found"
      continue-on-error: true
