name: "Test NixOS Configuration"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Prepare /usr/share/wallpaper and update flake.lock hash/timestamp
      run: |
        sudo mkdir -p /usr/share/wallpaper
        echo "dummy" | sudo tee /usr/share/wallpaper/dummy.jpg
        echo "nix hash path output:"
        nix hash path /usr/share/wallpaper
        HASH=$(nix hash path /usr/share/wallpaper)
        echo "Extracted HASH: $HASH"
        NOW=$(stat -c %Y /usr/share/wallpaper)
        echo "Calculated lastModified: $NOW"
        echo "Before edit:"
        # Extract just the wallpapers entry
        sed -n '/"wallpapers": {/,/^    },$/p' flake.lock > wallpapers_block.tmp
        cat wallpapers_block.tmp
        if [ -z "$HASH" ]; then echo "ERROR: HASH is empty!"; exit 1; fi
        echo "DEBUG: wallpapers_block.tmp contents before lastModified edit:"
        cat wallpapers_block.tmp
        # Only modify the first occurrence of lastModified (in the locked section)
        sed -i '0,/"lastModified": [0-9]\+,/{s|"lastModified": [0-9]\+,|"lastModified": '"$NOW"',|}' wallpapers_block.tmp
        sed -i 's|"narHash": "[^"]*"|"narHash": "'"$HASH"'"|' wallpapers_block.tmp
        echo "Modified wallpapers block:"
        cat wallpapers_block.tmp
        # Replace the wallpapers block using a temporary file approach
        grep -n '"wallpapers": {' flake.lock | cut -d: -f1 > start_line.tmp
        grep -n '^    },$' flake.lock | head -n1 | cut -d: -f1 > end_line.tmp
        START=$(cat start_line.tmp)
        END=$(cat end_line.tmp)
        echo "Replacing lines $START to $END"
        head -n $((START-1)) flake.lock > flake.lock.new
        cat wallpapers_block.tmp >> flake.lock.new
        tail -n +$((END+1)) flake.lock >> flake.lock.new
        mv flake.lock.new flake.lock
        rm start_line.tmp end_line.tmp
        echo "After edit:"
        sed -n '/"wallpapers": {/,/^    },$/p' flake.lock
        BLOCK=$(sed -n '/"wallpapers": {/,/^    },$/p' flake.lock)
        if [ -z "$BLOCK" ]; then echo "ERROR: wallpapers block is empty after edit!"; exit 1; fi
        rm wallpapers_block.tmp
    - name: Check flake syntax
      run: nix flake check --verbose

    - name: Evaluate NixOS configuration
      run: |
        nix eval .#nixosConfigurations.centaur.config.system.build.toplevel.drvPath \
          --verbose

    - name: Check for common issues
      run: |
        echo "Checking for common configuration issues..."
        
        # Check if all imports exist
        echo "Verifying all imports are accessible..."
        nix eval .#nixosConfigurations.centaur.options --apply 'x: "imports-ok"' || echo "Import check failed"
        
        # Check if home-manager is properly configured
        echo "Checking home-manager integration..."
        nix eval .#nixosConfigurations.centaur.config.home-manager --apply 'x: "hm-ok"' || echo "Home-manager not configured"
        
        echo "Basic checks completed!"

  dry-build:
    runs-on: ubuntu-latest
    needs: basic-check
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Dry build NixOS configuration
      run: |
        nix build .#nixosConfigurations.centaur.config.system.build.toplevel \
          --dry-run \
          --verbose
